services:
  azure-frontend-service: 
    image: jacobperssons/azure-frontend:latest
    ports: 
      - "80:3000"
    restart: always

  azure-backend-service: 
    image: jacobperssons/azure-backend:latest
    ports: 
      - "8080:8080"
    restart: always
